server:
  port: 8080

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: username
      password: password
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

